# Generated by Django 3.0.8 on 2022-06-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='author',
            field=models.CharField(default='not stated', max_length=250),
        ),
    ]
