# Generated by Django 3.0.8 on 2022-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20220613_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='author',
            field=models.CharField(max_length=250),
        ),
    ]
