# Generated by Django 3.0.8 on 2022-06-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20220613_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Cert',
            new_name='cert',
        ),
    ]
